
ALTER TABLE public.company_profiles
  ADD COLUMN IF NOT EXISTS turnover_y1 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS turnover_y2 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS turnover_y3 text DEFAULT '',
  ADD COLUMN IF NOT EXISTS net_worth text DEFAULT '',
  ADD COLUMN IF NOT EXISTS gem_seller_id text DEFAULT '',
  ADD COLUMN IF NOT EXISTS nsic_number text DEFAULT '',
  ADD COLUMN IF NOT EXISTS duns_number text DEFAULT '',
  ADD COLUMN IF NOT EXISTS iso_number text DEFAULT '',
  ADD COLUMN IF NOT EXISTS iso_expiry text DEFAULT '',
  ADD COLUMN IF NOT EXISTS bis_number text DEFAULT '',
  ADD COLUMN IF NOT EXISTS stqc_number text DEFAULT '',
  ADD COLUMN IF NOT EXISTS bee_rating text DEFAULT '',
  ADD COLUMN IF NOT EXISTS epf_code text DEFAULT '',
  ADD COLUMN IF NOT EXISTS esic_code text DEFAULT '',
  ADD COLUMN IF NOT EXISTS additional_gsts text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS business_type text DEFAULT '',
  ADD COLUMN IF NOT EXISTS dsc_expiry text DEFAULT '',
  ADD COLUMN IF NOT EXISTS dd_bank text DEFAULT '',
  ADD COLUMN IF NOT EXISTS dd_favouring text DEFAULT '',
  ADD COLUMN IF NOT EXISTS mii_class text DEFAULT 'Class-I',
  ADD COLUMN IF NOT EXISTS land_border_equity boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS subletting_allowed boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS office_state text DEFAULT '';
